NAME        := fixed
CXX         := c++
CXXFLAGS    := -Wall -Wextra -Werror -std=c++98
SRC         := main.cpp Fixed.cpp Point.cpp bsp.cpp
OBJ         := $(SRC:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(OBJ) -o $(NAME)

%.o: %.CXX
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
